# SCRAPING & CLEANING DATA
I used pandas for scraping data (instead of beautifulsoup, requests, urllib3...) because it requires short code and its faster, besides I am more familiar with it for scraping tabular data.

In [ ]:
import numpy as np
import pandas as pd
import datetime as dt
import matplotlib.pyplot as mlp
import seaborn as sns
import sklearn as skl

# KEYS & ABBREVIATIONS...
I used a lot of abbreviations in declaring variables for the various data, I need to explain them (20-21) here

1 ecff = Employment in crop farming(Female)

2 ecfm = Employment in crop farming(Male)

3 cfff = Crop farming: Farmers(Female)

4 cffm = Crop farming: Farmers (Male)

5 cfpef = Crop farming: Paid emlpoyee(Female)

6 cfpem = Crop farming: Paid employee(Male)

7 cfuff = Crop farming: Unpaid family(Female)

8 cfufm = Crop farming: Unpaid family(Male)

9 UER = Unemployment rate

10 tp = Total population

11 rf = Annual rainfall

12 hm = mean annual relative humidity

13 hs = household size

14 go = Graduate output from college

15 pd1 = Population living on dollar

16 ie= income inequality

17 pi = Poverty income

18 arc = Armed robbery Cases

19 sv = Stollen vehicles

20 mp= Missing person

# Declaring variables with keys and scraping with 'read_html' function in pandas

In [ ]:
ecff=pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Employment-in-crop-farming-Female' )
ecff1=pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Employment-in-crop-farming-Female' )[0]
ecfm=pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Employment-in-crop-farming-Male', )
cfff=(pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Crop-farming-Farmers-Female', ))
cffm=(pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Crop-farming-Farmers-Male',  )) 
cfpef=(pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Crop-farming-Paid-emlpoyee-Female',  )) 
cfpem=(pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Crop-farming-Paid-employee-Male'))  
cfuff=(pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Crop-farming-Unpaid-family-Female',  ))   
cfufm=(pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Crop-farming-Unpaid-family-Male',  ))    
UER=(pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Unemployment-rate',  ))     
tp=pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Total-Population')
rf=pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Annual-Rainfall')
hm=pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Annual-Mean-Relative-Humidity-at-0900-Gmt') 
hs=pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Household-Size')
go=pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Graduate-output-from-colleges-of-education') 
pd1= pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Population-living-on-dollar1')
ie= pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Income-inequality')
pi= pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Poverty-Incidence') 
arc=pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Number-of-Reported-Armed-Robbery-Cases')
sv=pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Number-of-Stolen-Vehicles') 
mp=pd.read_html('https://nigeria.opendataforafrica.org/apps/atlas/Osun/Number-of-Missing-Persons')

htables= ecff, ecfm, cfff,  cffm, cfpef, cfpem, cfuff, cfufm, UER, tp, rf, hm, hs, pd1, go, ie, pi, arc, mp, sv
print(htables)

([    Date  Value Change, %
0   2006  183.0   -3.68 %
1   2005  190.0   -5.47 %
2   2004  201.0    6.35 %
3   2003  189.0    6.78 %
4   2002  177.0   -2.21 %
5   2001  181.0  -44.82 %
6   2000  328.0   10.81 %
7   1999  296.0   59.14 %
8   1998  186.0    5.08 %
9   1997  177.0   17.22 %
10  1996  151.0    0.67 %
11  1995  150.0       NaN], [    Date  Value Change, %
0   2006  308.0   -3.14 %
1   2005  318.0   -5.92 %
2   2004  338.0    6.29 %
3   2003  318.0    7.07 %
4   2002  297.0   -1.98 %
5   2001  303.0   -7.90 %
6   2000  329.0   11.15 %
7   1999  296.0   -5.43 %
8   1998  313.0    5.03 %
9   1997  298.0   17.79 %
10  1996  253.0    0.40 %
11  1995  252.0       NaN], [    Date  Value Change, %
0   2006   15.0   -6.25 %
1   2005   16.0  -11.11 %
2   2004   18.0    5.88 %
3   2003   17.0    6.25 %
4   2002   16.0    0.00 %
5   2001   16.0  -44.83 %
6   2000   29.0   11.54 %
7   1999   26.0   62.50 %
8   1998   16.0    6.67 %
9   1997   15.0   15.38 %
10  1996   13.0    0.00 %
11  

In [ ]:

#ECFF
df_ecff=ecff[0]
df_date=df_ecff['Date']
df_ecff_value=df_ecff['Value']
#ECFM
df_ecfm=ecfm[0]
df_ecfm_value=df_ecfm['Value']
#CFFF
df_cfff=cfff[0]
df_cfff_value=df_cfff['Value']
#CFFM
df_cffm=cffm[0]
df_cffm_value=df_cffm['Value']
#CFPEF
df_cfpef=cfpef[0]
df_cfpef_value=df_cfpef['Value']
#CFPEM
df_cfpem=cfpem[0]
df_cfpem_value=df_cfpem['Value']
#CFUFF
df_cfuff=cfuff[0]
df_cfuff_value=df_cfuff['Value']
#CFUFM
df_cfufm=cfufm[0]
df_cfufm_value=df_cfufm['Value']
#UER
df_UER=UER[0]
df_UER_value=df_UER['Value']
df_tp=tp[0]
df_tp_value=df_tp['Value']
df_rf=rf[0]
df_rf_value=df_rf['Value']
df_hm=hm[0]
df_hm_value=df_hm['Value']
df_hs=hs[0]
df_hs_value=df_hs['Value']
df_go=go[0]
df_go_value=df_go['Value']
df_pd1=pd1[0]
df_pd1_value=df_pd1['Value']
df_ie=ie[0]
df_ie_value=df_ie['Value']
df_pi=pi[0]
df_pi_value=df_pi['Value']
df_arc=arc[0]
df_arc_value=df_arc['Value']
df_sv=sv[0]
df_sv_value=df_sv['Value']
df_mp=mp[0]
df_mp_value=df_mp['Value']

Create a new table and add the DataFrames into the columns

In [ ]:
table={'ID':[1,2,3,4,5,6,7,8,9,10,11]}

dft=pd.DataFrame(table)
dft['Date']=df_date
dft['ECFF']=df_ecff_value
dft['ECFM']=df_ecfm_value 
dft['CFFF']=df_cfff_value 
dft['CFFM']=df_cffm_value 
dft['CFPEF']=df_cfpef_value 
dft['CFPEM']=df_cfpem_value
dft['CFUFF']=df_cfuff_value
dft['CFUFM']=df_cfufm_value
dft['UER']=df_UER_value
dft['PD']=df_pd1_value
dft['GO']=df_go_value
dft['HS']=df_hs_value
dft['HM']=df_hm_value
dft['RF']=df_rf_value
dft['TP']=df_tp_value
dft['MP']=df_mp_value
dft['SV']=df_sv_value
dft['IE']=df_ie_value
dft['ARC']=df_arc_value
dft['PI']=df_pi_value

print(dft)

    ID  Date   ECFF   ECFM  CFFF  ...    MP    SV    IE   ARC    PI
0    1  2006  183.0  308.0  15.0  ...   7.0  22.0  0.39  18.0  57.0
1    2  2005  190.0  318.0  16.0  ...   7.0  25.0  0.33  27.0  32.4
2    3  2004  201.0  338.0  18.0  ...  57.0  46.0   NaN  16.0   NaN
3    4  2003  189.0  318.0  17.0  ...   1.0  47.0   NaN  21.0   NaN
4    5  2002  177.0  297.0  16.0  ...  15.0  12.0   NaN  51.0   NaN
5    6  2001  181.0  303.0  16.0  ...  74.0   3.0   NaN  31.0   NaN
6    7  2000  328.0  329.0  29.0  ...  51.0  62.0   NaN  17.0   NaN
7    8  1999  296.0  296.0  26.0  ...  27.0   NaN   NaN   NaN   NaN
8    9  1998  186.0  313.0  16.0  ...  21.0   NaN   NaN   NaN   NaN
9   10  1997  177.0  298.0  15.0  ...   NaN   NaN   NaN   NaN   NaN
10  11  1996  151.0  253.0  13.0  ...   NaN   NaN   NaN   NaN   NaN

[11 rows x 22 columns]


In [ ]:
print(dft.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ID      11 non-null     int64  
 1   Date    11 non-null     int64  
 2   ECFF    11 non-null     float64
 3   ECFM    11 non-null     float64
 4   CFFF    11 non-null     float64
 5   CFFM    11 non-null     float64
 6   CFPEF   11 non-null     float64
 7   CFPEM   11 non-null     float64
 8   CFUFF   11 non-null     float64
 9   CFUFM   11 non-null     float64
 10  UER     11 non-null     float64
 11  PD      2 non-null      float64
 12  GO      4 non-null      float64
 13  HS      5 non-null      float64
 14  HM      6 non-null      float64
 15  RF      5 non-null      float64
 16  TP      6 non-null      float64
 17  MP      9 non-null      float64
 18  SV      7 non-null      float64
 19  IE      2 non-null      float64
 20  ARC     7 non-null      float64
 21  PI      2 non-null      float64
dtypes: f

# To make Time-series analysis easier
I created a new date object with pandas using 'date_range'

In [ ]:
date=pd.date_range(end='2007-1-1',freq='Y', periods=11)
print((date.year)[::-1])
dft['Date']=(date.year)[::-1]

Int64Index([2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996], dtype='int64')


In [ ]:
print (dft)

    ID  Date   ECFF   ECFM  CFFF  ...    MP    SV    IE   ARC    PI
0    1  2006  183.0  308.0  15.0  ...   7.0  22.0  0.39  18.0  57.0
1    2  2005  190.0  318.0  16.0  ...   7.0  25.0  0.33  27.0  32.4
2    3  2004  201.0  338.0  18.0  ...  57.0  46.0   NaN  16.0   NaN
3    4  2003  189.0  318.0  17.0  ...   1.0  47.0   NaN  21.0   NaN
4    5  2002  177.0  297.0  16.0  ...  15.0  12.0   NaN  51.0   NaN
5    6  2001  181.0  303.0  16.0  ...  74.0   3.0   NaN  31.0   NaN
6    7  2000  328.0  329.0  29.0  ...  51.0  62.0   NaN  17.0   NaN
7    8  1999  296.0  296.0  26.0  ...  27.0   NaN   NaN   NaN   NaN
8    9  1998  186.0  313.0  16.0  ...  21.0   NaN   NaN   NaN   NaN
9   10  1997  177.0  298.0  15.0  ...   NaN   NaN   NaN   NaN   NaN
10  11  1996  151.0  253.0  13.0  ...   NaN   NaN   NaN   NaN   NaN

[11 rows x 22 columns]


# The next step is a dicey one
There'shere's a lot of missing data 'NaN' . This might cause a biased analysis or model. The two possible solutions is to either delete missing data or fill missing data.
We shall go for the latter one, however filling missing data depends on whether it's random or not.Random mising data is best solved by either filling with mean of the total missing columns or filling with next/previous available data(fill pad).
This one is non-Random so we are using imputation by linear regression model.
I couldn't split the data because there's only few data. 
Hence the available data is used to predict the missing data.
The independent variable (x) is Date, while the target variable is the available data.

It's a tedious one though

In [ ]:
from sklearn.linear_model import LinearRegression as lr
model=lr()

x1=dft[['Date']][0:2]
y1=dft['PD'][0:2]
pd1=model.fit(x1,y1)
pm1=model.predict(dft[['Date']][2:11])
print(pm1)

x=dft[['Date']][0:4]
y=dft['GO'][0:4]
go=model.fit(x,y)
gm=model.predict(dft[['Date']][4:11])
print(gm)

[  -0.7  -24.1  -47.5  -70.9  -94.3 -117.7 -141.1 -164.5 -187.9]
[8721.5 7575.2 6428.9 5282.6 4136.3 2990.  1843.7]


Repeat for other features with missing values.

In [ ]:
x2=dft[['Date']][0:5]
y2=dft['HS'][0:5]
hs=model.fit(x2,y2)
hs1=model.predict(dft[['Date']][5:11])
print(hs1)


x3=dft[['Date']][0:6]
y3=dft['HM'][0:6]
hm=model.fit(x3,y3)
hm=model.predict(dft[['Date']][6:11])
print(hm)


x4=dft[['Date']][0:5]
y4=dft['RF'][0:5]
rf=model.fit(x4,y4)
rm=model.predict(dft[['Date']][5:11])
print(rm)

x5=dft[['Date']][0:6]
y5=dft['TP'][0:6]
tp=model.fit(x5,y5)
tm=model.predict(dft[['Date']][6:11])
print(tm)


x6=dft[['Date']][0:9]
y6=dft['MP'][0:9]
mp=model.fit(x6,y6)
mm=model.predict(dft[['Date']][9:11])
print(mm)

x7=dft[['Date']][0:7]
y7=dft['SV'][0:7]
sv=model.fit(x7,y7)
sm=model.predict(dft[['Date']][7:11])
print(sm)


x8=dft[['Date']][0:2]
y8=dft['IE'][0:2]
ie=model.fit(x8,y8)
im=model.predict(dft[['Date']][2:11])
print(im)


x9=dft[['Date']][0:7]
y9=dft['ARC'][0:7]
ars=model.fit(x9,y9)
arm=model.predict(dft[['Date']][7:11])
print(arm)


x10=dft[['Date']][0:2]
y10=dft['PI'][0:2]
pi=model.fit(x10,y10)
pm=model.predict(dft[['Date']][2:11])
print(pm)



[3.39 3.24 3.09 2.94 2.79 2.64]
[79.18666667 78.9352381  78.68380952 78.43238095 78.18095238]
[1252.51 1210.22 1167.93 1125.64 1083.35 1041.06]
[3326871.80000001 3190976.17142856 3055080.54285717 2919184.91428572
 2783289.28571427]
[43.63888889 46.58888889]
[37.  38.5 40.  41.5]
[ 0.27  0.21  0.15  0.09  0.03 -0.03 -0.09 -0.15 -0.21]
[31.57142857 33.         34.42857143 35.85714286]
[   7.8  -16.8  -41.4  -66.   -90.6 -115.2 -139.8 -164.4 -189. ]


I was able to predict the missing values in assumption that it follows a linear  pattern. 
However, the result for 'IE' is negative because of few available value, so the slope was very high.

# Lastly, I merged the predicted values with there respective available values using the pandas concat function.
Note the slicing I did and the 'ignore_index'. Without it there will be Error notice.

In [ ]:
dt=pd.DataFrame(pm1)
concat=pd.concat([dft['PD'][0:2], dt], ignore_index=True)
dft['PD1']= concat
print(dft['PD'])


dt=pd.DataFrame(gm)
concat=pd.concat([dft['GO'][0:4], dt], ignore_index=True)
dft['GO']= concat
print(dft['GO'])

 

0     46.1
1     22.7
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
10     NaN
Name: PD, dtype: float64
0     11956.0
1     13953.0
2     11481.0
3      8959.0
4      8721.5
5      7575.2
6      6428.9
7      5282.6
8      4136.3
9      2990.0
10     1843.7
Name: GO, dtype: float64


Repeat for others

In [ ]:
dt=pd.DataFrame(hs1)
concat=pd.concat([dft['HS'][0:5], dt], ignore_index=True)
dft['HS']= concat
 
dt=pd.DataFrame(hm)
concat=pd.concat([dft['HM'][0:6], dt], ignore_index=True)
dft['HM']= concat
 
 
dt=pd.DataFrame(rm)
concat=pd.concat([dft['RF'][0:5], dt], ignore_index=True)
dft['RF']= concat
 
 
dt=pd.DataFrame(tm)
concat=pd.concat([dft['TP'][0:6], dt], ignore_index=True)
dft['TP']= concat
 
dt=pd.DataFrame(mm)
concat=pd.concat([dft['MP'][0:9], dt], ignore_index=True)
dft['MP']= concat
 
 
dt=pd.DataFrame(sm)
concat=pd.concat([dft['SV'][0:7], dt], ignore_index=True)
dft['SV']= concat
 
 
dt=pd.DataFrame(im)
concat=pd.concat([dft['IE'][0:2], dt], ignore_index=True)
dft['IE1']= concat
 
dt=pd.DataFrame(arm)
concat=pd.concat([dft['ARC'][0:7], dt], ignore_index=True)
dft['ARC']= concat
 
 
dt=pd.DataFrame(pm)
concat=pd.concat([dft['PI'][0:2], dt], ignore_index=True)
dft['PI1']= concat
 
 
 
print(dft)

    ID  Date   ECFF   ECFM  CFFF  ...        ARC    PI    PD1   IE1    PI1
0    1  2006  183.0  308.0  15.0  ...  18.000000  57.0   46.1  0.39   57.0
1    2  2005  190.0  318.0  16.0  ...  27.000000  32.4   22.7  0.33   32.4
2    3  2004  201.0  338.0  18.0  ...  16.000000   NaN   -0.7  0.27    7.8
3    4  2003  189.0  318.0  17.0  ...  21.000000   NaN  -24.1  0.21  -16.8
4    5  2002  177.0  297.0  16.0  ...  51.000000   NaN  -47.5  0.15  -41.4
5    6  2001  181.0  303.0  16.0  ...  31.000000   NaN  -70.9  0.09  -66.0
6    7  2000  328.0  329.0  29.0  ...  17.000000   NaN  -94.3  0.03  -90.6
7    8  1999  296.0  296.0  26.0  ...  31.571429   NaN -117.7 -0.03 -115.2
8    9  1998  186.0  313.0  16.0  ...  33.000000   NaN -141.1 -0.09 -139.8
9   10  1997  177.0  298.0  15.0  ...  34.428571   NaN -164.5 -0.15 -164.4
10  11  1996  151.0  253.0  13.0  ...  35.857143   NaN -187.9 -0.21 -189.0

[11 rows x 25 columns]


Using linear regression for imputation method has its benefits, however, in cases of datasets with few values, it perform woefully because of the high gradient slope. This gives negatives values as seen in (PD, IE & PI).
To solve this problem, impute the missing values with the last minimum vale.

In [ ]:
dft['PD']=dft['PD'].fillna(22.7)
dft['IE']=dft['IE'].fillna(0.03)
dft['PI']=dft['PI'].fillna(32.4)

In [ ]:
print(dft['IE'])
print(dft['PD'])
print(dft['PI'])

0     0.39
1     0.33
2     0.03
3     0.03
4     0.03
5     0.03
6     0.03
7     0.03
8     0.03
9     0.03
10    0.03
Name: IE, dtype: float64
0     46.1
1     22.7
2     22.7
3     22.7
4     22.7
5     22.7
6     22.7
7     22.7
8     22.7
9     22.7
10    22.7
Name: PD, dtype: float64
0     57.0
1     32.4
2     32.4
3     32.4
4     32.4
5     32.4
6     32.4
7     32.4
8     32.4
9     32.4
10    32.4
Name: PI, dtype: float64


In [ ]:
dft.pop('PD1')
dft.pop('IE1')
dft.pop('PI1')

0      57.0
1      32.4
2       7.8
3     -16.8
4     -41.4
5     -66.0
6     -90.6
7    -115.2
8    -139.8
9    -164.4
10   -189.0
Name: PI1, dtype: float64

In [ ]:
print(dft)

    ID  Date   ECFF   ECFM  CFFF  ...         MP    SV    IE        ARC    PI
0    1  2006  183.0  308.0  15.0  ...   7.000000  22.0  0.39  18.000000  57.0
1    2  2005  190.0  318.0  16.0  ...   7.000000  25.0  0.33  27.000000  32.4
2    3  2004  201.0  338.0  18.0  ...  57.000000  46.0  0.03  16.000000  32.4
3    4  2003  189.0  318.0  17.0  ...   1.000000  47.0  0.03  21.000000  32.4
4    5  2002  177.0  297.0  16.0  ...  15.000000  12.0  0.03  51.000000  32.4
5    6  2001  181.0  303.0  16.0  ...  74.000000   3.0  0.03  31.000000  32.4
6    7  2000  328.0  329.0  29.0  ...  51.000000  62.0  0.03  17.000000  32.4
7    8  1999  296.0  296.0  26.0  ...  27.000000  37.0  0.03  31.571429  32.4
8    9  1998  186.0  313.0  16.0  ...  21.000000  38.5  0.03  33.000000  32.4
9   10  1997  177.0  298.0  15.0  ...  43.638889  40.0  0.03  34.428571  32.4
10  11  1996  151.0  253.0  13.0  ...  46.588889  41.5  0.03  35.857143  32.4

[11 rows x 22 columns]


In [ ]:
dft.pop('ID')

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
Name: ID, dtype: int64

In [ ]:
print(dft)

    Date   ECFF   ECFM  CFFF   CFFM  ...         MP    SV    IE        ARC    PI
0   2006  183.0  308.0  15.0  162.0  ...   7.000000  22.0  0.39  18.000000  57.0
1   2005  190.0  318.0  16.0  167.0  ...   7.000000  25.0  0.33  27.000000  32.4
2   2004  201.0  338.0  18.0  170.0  ...  57.000000  46.0  0.03  16.000000  32.4
3   2003  189.0  318.0  17.0  160.0  ...   1.000000  47.0  0.03  21.000000  32.4
4   2002  177.0  297.0  16.0  150.0  ...  15.000000  12.0  0.03  51.000000  32.4
5   2001  181.0  303.0  16.0  153.0  ...  74.000000   3.0  0.03  31.000000  32.4
6   2000  328.0  329.0  29.0  166.0  ...  51.000000  62.0  0.03  17.000000  32.4
7   1999  296.0  296.0  26.0  149.0  ...  27.000000  37.0  0.03  31.571429  32.4
8   1998  186.0  313.0  16.0  165.0  ...  21.000000  38.5  0.03  33.000000  32.4
9   1997  177.0  298.0  15.0  157.0  ...  43.638889  40.0  0.03  34.428571  32.4
10  1996  151.0  253.0  13.0  133.0  ...  46.588889  41.5  0.03  35.857143  32.4

[11 rows x 21 columns]


# FINALLY, OUR DATA IS AVAILABLE, SCRAPED & CLEANED. LETS SAVE IT.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data=dft.to_excel(r'/content/drive/MyDrive/Colab Notebooks/OSUN UNEMPLOYMENT RATE/data.xlsx', index=False, header=True)